export const Colors = {
  primary: "#1A1A1A",
  secondary: "#1A1A1A9C",
  tertiary: "#CCCCCC",
  quaternary: "#0069FF",
  lightgray: "#DADADA",
  lightwhite: "#FBFCFD",
  darkgray: "#B2B2B2",
  danger: "#FF0000",
  lightzinc: "#f1eeee",
  darkzinc: "#F9F9F9",
  redwhite: "#F2F2F2",
  bluewhite: "#F2F8FF",
  lightwhitered: "#FAFAFA",
  greenShade: "#00E396",
  pinkShade: "#FF4560",
  blueShade: "#0099FF",
};
